version: '3.8'

services:
  web:
    build:
      context: .
    image: dhruvinnvonix/warmup:0.0.1
    ports:
      - "8000:8000"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .docker.env
    dns:
      - 1.1.1.1
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - ./data:/var/lib/postgresql
    env_file:
      - .docker.env
