# Generated by Django 4.0.6 on 2023-01-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(default='', max_length=150)),
                ('password', models.CharField(default='', max_length=200)),
                ('smtp_port', models.CharField(default='', max_length=15)),
                ('smtp_host', models.CharField(default='', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('number_of_days_to_warmup', models.IntegerField(default=60)),
                ('app_pass_phrase', models.CharField(default='', max_length=200)),
                ('number_of_emails_sent', models.IntegerField(default=0)),
                ('email_type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='GmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=200)),
                ('app_pass_phrase', models.CharField(default='', max_length=200)),
                ('imap_port', models.CharField(default='', max_length=15)),
                ('smtp_port', models.CharField(default='', max_length=15)),
                ('smtp_host', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OtherRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=200)),
                ('app_pass_phrase', models.CharField(default='', max_length=200)),
                ('imap_port', models.CharField(default='', max_length=15)),
                ('smtp_port', models.CharField(default='', max_length=15)),
                ('smtp_host', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OutlookRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=200)),
                ('app_pass_phrase', models.CharField(default='', max_length=200)),
                ('imap_port', models.CharField(default='', max_length=15)),
                ('smtp_port', models.CharField(default='', max_length=15)),
                ('smtp_host', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=200)),
                ('app_pass_phrase', models.CharField(default='', max_length=200)),
                ('imap_port', models.CharField(default='', max_length=15)),
                ('smtp_port', models.CharField(default='', max_length=15)),
                ('smtp_host', models.CharField(default='', max_length=50)),
                ('email_type', models.CharField(default='', max_length=50)),
                ('today_email_sent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.TimeField()),
                ('reply_time', models.TimeField()),
            ],
        ),
    ]
