# Generated by Django 4.0.6 on 2023-04-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_warmup', '0002_otherrecipient_imap_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailrecipient',
            name='imap_host',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='outlookrecipient',
            name='imap_host',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='temporaryrecipient',
            name='imap_host',
            field=models.CharField(default='', max_length=50),
        ),
    ]
