# Generated by Django 4.0.6 on 2024-04-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_warmup', '0003_gmailrecipient_imap_host_outlookrecipient_imap_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailimprovement',
            name='app_pass_phrase',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
